# For more information: https://laravel.com/docs/sail
services:
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: app
        ports:
            - '8000:${APP_PORT:-80}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
            - './storage/app/temp:/temp'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        expose:
            - '3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
    r:
        build:
            context: ./docker/R/
            dockerfile: Dockerfile
        image: r
        expose:
            - '6311'
        networks:
            - sail
        volumes:
            - './storage/app/public/arquivos:/arquivos'
            - './storage/app/temp:/temp'
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
