name: Laravel-Docker-Cypress

on:
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install
      run: ./deploy.sh
    - name: Generate key
      run: docker exec notar_app_1 php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: docker exec -t notar_app_1 php artisan migrate
    - name: Execute tests
      run: npx cypress run
