name: Cypress

on:
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set permissions
      run: sudo chmod -R 777 storage bootstrap/cache
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.cypress', '.env');"
    - name: Install
      run: ./deploy.sh
    - name: Create Database
      run: docker exec -t notar_app_1 php artisan migrate
    - name: Create admin user
      run: docker exec -t notar_app_1 php artisan migrate:admin novasenha
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        config-file: cypress.config.js
